# Generated by Django 4.1.5 on 2023-02-28 13:17

import disablepeoplee.models
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CameraInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cameraip', models.IntegerField()),
                ('date_created', models.DateField(verbose_name='تاریخ تشخیص')),
            ],
            options={
                'verbose_name': ' دوربین',
                'verbose_name_plural': 'دوربین ها',
            },
        ),
        migrations.CreateModel(
            name='Detects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classobj', models.IntegerField()),
                ('boundry', models.CharField(max_length=60, verbose_name='مختصات ')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='تاریخ تشخیص')),
                ('date2', django_jalali.db.models.jDateField()),
                ('img', models.ImageField(upload_to=disablepeoplee.models.mainproductFile, verbose_name='فریم')),
                ('lightflag', models.BooleanField(blank=True, default=False, null=True, verbose_name='چراغ')),
                ('cameraid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disablepeoplee.camerainfo')),
            ],
            options={
                'verbose_name': 'اشیا تشخیص داده شده',
                'verbose_name_plural': 'اشیا تشخیص داده شده',
            },
        ),
    ]
