# Generated by Django 4.1.5 on 2023-03-04 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disablepeoplee', '0002_mytoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detects',
            name='cameraid',
        ),
    ]
