# Generated by Django 4.1.5 on 2023-03-04 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disablepeoplee', '0003_remove_detects_cameraid'),
    ]

    operations = [
        migrations.AddField(
            model_name='detects',
            name='cameraid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='disablepeoplee.camerainfo'),
        ),
    ]
